version: '3'
services:
  recsys:
    container_name: azrecsys
    build: .
    image: azrecsys
    ports:
      - "8265:8265"
      - "6006:6006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [ gpu ]
    volumes:
      - "./data:/home/app/data"
      - "./logs:/home/app/logs"
