version: '3'
services:
  recsys:
    container_name: azrecsys
    build: .
    shm_size: "10.24gb"
    image: azrecsys
    ports:
      - "8265:8265"
      - "6006:6006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - "./data:/home/app/data"
      - "./logs:/home/app/logs"
      - "./out:/home/app/out"
      - "./configs:/home/app/configs"
