data_class: toys.pkl
model_params:
  alpha: 0.1
  batch_size: 256
  d_model: 256
  dropout: 0.3
  heads: 2
  lambda_: 5
  mask_prob: 0.15
  max_len: 20
  n_layers: 2
  num_positive: 5
  temperature: 0.3
num_items: 11924
trainer_config:
  check_val_every_n_epoch: 10
  config_name: toys.cbit.default
  devices:
  - 1
  ks:
  - 1
  - 5
  - 10
  - 20
  label_smoothing: 0.0
  limit_train_batches: 1.0
  lr: 0.001
  max_epochs: 250
  num_workers: 6
  seed: 0
  weight_decay: 0
