data_class: beauty.pkl
# early_stopping:
#   mode: max
#   monitor: vae_recall@50
#   patience: 10
#   verbose: false
model_params:
  act_fn: tanh
  autoencoder_structure:
  - 512
  batch_size: 512
  beta: 0.5
  beta_annealing_epoch: 20
  hidden_dim: 128
  likelihood: mult
trainer_config:  
  devices:
  - 0
  limit_train_batches: 1.0
  lr: 0.001
  max_epochs: 100
  num_workers: 12
  seed: 0
