data_class: ml1m.pkl
model_params:
  activation: gelu
  attention_dropout: 0.3
  batch_size: 256
  d_model: 64
  dropout: 0.3
  heads: 2
  initializer_range: 0.02
  loss_type: ce
  max_len: 50
  n_layers: 2
num_items: 11924
trainer_config:
  check_val_every_n_epoch: 5
  devices:
  - 1
  ks:
  - 1
  - 5
  - 10
  - 20
  label_smoothing: 0.3
  limit_train_batches: 1.0
  lr: 0.001
  lr_scheduler: Warmup
  lr_scheduler_args:
    num_cycles: 0.2
    num_training_steps: 500
    num_warmup_steps: 200
  max_epochs: 50
  num_workers: 12
  seed: 0
  weight_decay: 0
