data_class: ml1m.pkl
model_params:
  batch_size: 256
  d_model: 256
  dropout: 0.2
  heads: 8
  item_latent_factor:
    available: true
    hidden_dim: 256
    path: /home/VS6102093/TVA/logs/ml1m.vaeicf.new/version_0/latent_factor/encode_result.npy
  mask_prob: 0.15
  max_len: 40
  n_layers: 2
  time_features:
  - dayofweek
  - months
  - years
trainer_config:
  check_val_every_n_epoch: 50
  config_name: ml1m.tva4.new
  devices:
  - 0
  ks:
  - 1
  - 5
  - 10
  - 20
  - 40
  label_smoothing: 0.0
  limit_train_batches: 1.0
  lr: 0.001
  lr_scheduler: Warmup
  lr_scheduler_args:
    num_cycles: 0.2
    num_training_steps: 82750
    num_warmup_steps: 10000
  lr_scheduler_interval: step
  max_epochs: 300
  num_workers: 12
  seed: 0
  sliding_step: 10
  sliding_window: true
