data_class: ratings_beauty_5.pkl
model_params:
  batch_size: 256
  d_model: 256
  dropout: 0.3
  heads: 8
  item_latent_factor:
    available: true
    hidden_dim: 256
    path: /home/VS6102093/TVA/logs/ratings_beauty_5.vaeicf.re/version_0/latent_factor/encode_result.npy
  mask_prob: 0.3
  max_len: 30
  n_layers: 2
  time_features:
  - dayofweek
  - months
  - years
trainer_config:
  check_val_every_n_epoch: 50
  config_name: ratings_beauty_5.tva4.best
  devices:
  - 0
  ks:
  - 1
  - 5
  - 10
  - 20
  label_smoothing: 0.35
  limit_train_batches: 1.0
  lr: 0.001
  lr_scheduler: Warmup
  lr_scheduler_args:
    num_cycles: 0.2
    num_training_steps: 32750
    num_warmup_steps: 6400
  lr_scheduler_interval: step
  max_epochs: 250
  num_workers: 6
  seed: 0
  sliding_step: 1
  sliding_window: true
  weight_decay: 0.0
