data_class: beauty.pkl
model_params:
  batch_size: 256
  d_model: 256
  dropout: 0.3
  heads: 2
  mask_prob: 0.15
  max_len: 15
  n_layers: 2
  num_mask: 5
num_items: 12101
trainer_config:
  check_val_every_n_epoch: 50
  config_name: beauty.bert4recs.re
  devices:
  - 1
  ks:
  - 1
  - 5
  - 10
  - 20
  - 40
  - 50
  label_smoothing: 0.0
  limit_train_batches: 1.0
  lr: 0.001
  max_epochs: 250
  num_workers: 6
  seed: 0
  weight_decay: 0
