data_class: beauty.pkl
model_params:
  act_fn: tanh
  autoencoder_structure:
  - 128
  batch_size: 512
  beta: 0.5
  hidden_dim: 256
  likelihood: mult
trainer_config:
  devices:
  - 0
  limit_train_batches: 1.0
  lr_scheduler: Warmup
  lr_scheduler_args:
    num_cycles: 0.2
    num_training_steps: 4300
    num_warmup_steps: 860
  lr_scheduler_interval: step
  max_epochs: 200
  num_workers: 12
  seed: 12345
